#!/usr/bin/python

import socket
port = 8081
host = '192.168.31.178'

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

def send(msg):
	s.sendto(msg, (host, port))

send('move 1030,600')
while(True):
	send('click')
